[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
build_flags =
    -std=gnu++17
build_unflags =
    -std=gnu++11
lib_deps =
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    https://github.com/schreibfaul1/ESP32-audioI2S.git
monitor_speed = 115200
